baseURL : https://freestuff.dev
languageCode : en
title : Free Dev Stuff

params:
    description: Free stuff for developer

staticDir: static

permalinks:
    blog : blog/:title/

summaryLength: 25

outputs:
    section : ["HTML", "RSS", "JSON"]

taxonomies:
    category : categories
    topic : topics
    tag : tags